name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish webdav to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: toby1991/fisco-bcos-browser
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tags: "latest,2.2.5"
